# Generated by Django 5.1.4 on 2024-12-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_remove_csvfile_title_delete_csvdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfile',
            options={'verbose_name': 'Plik CSV', 'verbose_name_plural': 'Pliki CSV'},
        ),
    ]
