# Generated by Django 5.1.4 on 2024-12-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_csvfile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='csvfile',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='csvfile',
            name='total_rows',
            field=models.IntegerField(default=0),
        ),
    ]
