# Generated by Django 5.1.4 on 2024-12-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_csvfile_progress_csvfile_status_csvfile_total_rows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvfile',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='csvfile',
            name='total_rows',
        ),
        migrations.AddField(
            model_name='csvfile',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='nazwa tublica'),
            preserve_default=False,
        ),
    ]
