# Generated by Django 5.1.4 on 2024-12-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_uploadedfile_original_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name': 'Plik', 'verbose_name_plural': 'Pliki'},
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='original_filename',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='nazwa tublica'),
            preserve_default=False,
        ),
    ]
