# Generated by Django 5.1.4 on 2024-12-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_alter_uploadedfile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={},
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='table_name',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
