# Generated by Django 5.1.4 on 2024-12-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_alter_uploadedfile_options_uploadedfile_table_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=100)),
                ('row_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Database Table',
                'verbose_name_plural': 'Database Tables',
                'managed': False,
            },
        ),
    ]
